services:
  service1:
    build:
      context: ./service-a
    ports:
      - "8001:8001"
    environment:
      - APP_ENV=local
    networks:
      - backend
    depends_on:
      - service1-db

  service1-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service1_db
    volumes:
      - service1-db-data:/var/lib/mysql
    networks:
      - backend

  service2:
    build:
      context: ./service-b
    ports:
      - "8002:8002"
    environment:
      - APP_ENV=local
    networks:
      - backend
    depends_on:
      - service2-db

  service2-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service2_db
    volumes:
      - service2-db-data:/var/lib/mysql
    networks:
      - backend

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  service1-db-data:
  service2-db-data:
